package ec.com.redepronik.negosys.wsOtros.broadnet.org.tempuri;

import java.net.MalformedURLException;
import java.net.URL;

import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;

/**
 * This class was generated by the JAX-WS RI. JAX-WS RI 2.2.6-1b01 Generated
 * source version: 2.2
 * 
 */
@WebServiceClient(name = "wsrecargas", targetNamespace = "http://tempuri.org/", wsdlLocation = "http://201.234.207.210/wsrecargas/wsrecargas.asmx?wsdl")
public class Wsrecargas extends Service {

	private static URL __getWsdlLocation() {
		if (WSRECARGAS_EXCEPTION != null) {
			throw WSRECARGAS_EXCEPTION;
		}
		return WSRECARGAS_WSDL_LOCATION;
	}

	private final static URL WSRECARGAS_WSDL_LOCATION;
	private final static WebServiceException WSRECARGAS_EXCEPTION;

	private final static QName WSRECARGAS_QNAME = new QName(
			"http://tempuri.org/", "wsrecargas");

	static {
		URL url = null;
		WebServiceException e = null;
		try {
			url = new URL(
					"http://201.234.207.210/wsrecargas/wsrecargas.asmx?wsdl");
		} catch (MalformedURLException ex) {
			e = new WebServiceException(ex);
		}
		WSRECARGAS_WSDL_LOCATION = url;
		WSRECARGAS_EXCEPTION = e;
	}

	public Wsrecargas() {
		super(__getWsdlLocation(), WSRECARGAS_QNAME);
	}

	public Wsrecargas(URL wsdlLocation) {
		super(wsdlLocation, WSRECARGAS_QNAME);
	}

	public Wsrecargas(URL wsdlLocation, QName serviceName) {
		super(wsdlLocation, serviceName);
	}

	public Wsrecargas(URL wsdlLocation, QName serviceName,
			WebServiceFeature... features) {
		super(wsdlLocation, serviceName, features);
	}

	public Wsrecargas(URL wsdlLocation, WebServiceFeature... features) {
		super(wsdlLocation, WSRECARGAS_QNAME, features);
	}

	public Wsrecargas(WebServiceFeature... features) {
		super(__getWsdlLocation(), WSRECARGAS_QNAME, features);
	}

	/**
	 * 
	 * @return returns WsrecargasSoap
	 */
	@WebEndpoint(name = "wsrecargasSoap")
	public WsrecargasSoap getWsrecargasSoap() {
		return super.getPort(
				new QName("http://tempuri.org/", "wsrecargasSoap"),
				WsrecargasSoap.class);
	}

	/**
	 * 
	 * @param features
	 *            A list of {@link javax.xml.ws.WebServiceFeature} to configure
	 *            on the proxy. Supported features not in the
	 *            <code>features</code> parameter will have their default
	 *            values.
	 * @return returns WsrecargasSoap
	 */
	@WebEndpoint(name = "wsrecargasSoap")
	public WsrecargasSoap getWsrecargasSoap(WebServiceFeature... features) {
		return super.getPort(
				new QName("http://tempuri.org/", "wsrecargasSoap"),
				WsrecargasSoap.class, features);
	}

	/**
	 * 
	 * @return returns WsrecargasSoap
	 */
	@WebEndpoint(name = "wsrecargasSoap12")
	public WsrecargasSoap getWsrecargasSoap12() {
		return super.getPort(new QName("http://tempuri.org/",
				"wsrecargasSoap12"), WsrecargasSoap.class);
	}

	/**
	 * 
	 * @param features
	 *            A list of {@link javax.xml.ws.WebServiceFeature} to configure
	 *            on the proxy. Supported features not in the
	 *            <code>features</code> parameter will have their default
	 *            values.
	 * @return returns WsrecargasSoap
	 */
	@WebEndpoint(name = "wsrecargasSoap12")
	public WsrecargasSoap getWsrecargasSoap12(WebServiceFeature... features) {
		return super.getPort(new QName("http://tempuri.org/",
				"wsrecargasSoap12"), WsrecargasSoap.class, features);
	}

}
