package ec.com.redepronik.negosys.wsOtros.broadnet.org.tempuri;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by the JAX-WS RI. JAX-WS RI 2.2.6-1b01 Generated
 * source version: 2.2
 * 
 */
@WebService(name = "wsrecargasSoap", targetNamespace = "http://tempuri.org/")
@XmlSeeAlso({ ObjectFactory.class })
public interface WsrecargasSoap {

	/**
	 * 
	 * @param codigoProceso
	 * @param lote
	 * @param servicio
	 * @param cajero
	 * @param autorizacion
	 * @param cupon
	 * @param mid
	 * @param tid
	 * @param cuenta
	 * @param proveedor
	 * @param clave
	 * @param referencia
	 * @param monto
	 * @param tipoTransaccion
	 * @return returns java.lang.String
	 */
	@WebMethod(action = "http://tempuri.org/peticionRequerimiento")
	@WebResult(name = "peticionRequerimientoResult", targetNamespace = "http://tempuri.org/")
	@RequestWrapper(localName = "peticionRequerimiento", targetNamespace = "http://tempuri.org/", className = "org.tempuri.PeticionRequerimiento")
	@ResponseWrapper(localName = "peticionRequerimientoResponse", targetNamespace = "http://tempuri.org/", className = "org.tempuri.PeticionRequerimientoResponse")
	public String peticionRequerimiento(
			@WebParam(name = "tipoTransaccion", targetNamespace = "http://tempuri.org/") String tipoTransaccion,
			@WebParam(name = "codigoProceso", targetNamespace = "http://tempuri.org/") String codigoProceso,
			@WebParam(name = "monto", targetNamespace = "http://tempuri.org/") String monto,
			@WebParam(name = "cajero", targetNamespace = "http://tempuri.org/") String cajero,
			@WebParam(name = "clave", targetNamespace = "http://tempuri.org/") String clave,
			@WebParam(name = "tid", targetNamespace = "http://tempuri.org/") String tid,
			@WebParam(name = "mid", targetNamespace = "http://tempuri.org/") String mid,
			@WebParam(name = "proveedor", targetNamespace = "http://tempuri.org/") String proveedor,
			@WebParam(name = "servicio", targetNamespace = "http://tempuri.org/") String servicio,
			@WebParam(name = "cuenta", targetNamespace = "http://tempuri.org/") String cuenta,
			@WebParam(name = "autorizacion", targetNamespace = "http://tempuri.org/") String autorizacion,
			@WebParam(name = "referencia", targetNamespace = "http://tempuri.org/") String referencia,
			@WebParam(name = "lote", targetNamespace = "http://tempuri.org/") String lote,
			@WebParam(name = "cupon", targetNamespace = "http://tempuri.org/") String cupon);

	/**
	 * 
	 * @param lote
	 * @param cantidad
	 * @param idproducto
	 * @param cupon
	 * @param mid
	 * @param tid
	 * @param cuenta
	 * @param referencia
	 * @return returns java.lang.String
	 */
	@WebMethod(action = "http://tempuri.org/redimirCupoMarca")
	@WebResult(name = "redimirCupoMarcaResult", targetNamespace = "http://tempuri.org/")
	@RequestWrapper(localName = "redimirCupoMarca", targetNamespace = "http://tempuri.org/", className = "org.tempuri.RedimirCupoMarca")
	@ResponseWrapper(localName = "redimirCupoMarcaResponse", targetNamespace = "http://tempuri.org/", className = "org.tempuri.RedimirCupoMarcaResponse")
	public String redimirCupoMarca(
			@WebParam(name = "tid", targetNamespace = "http://tempuri.org/") String tid,
			@WebParam(name = "mid", targetNamespace = "http://tempuri.org/") String mid,
			@WebParam(name = "cuenta", targetNamespace = "http://tempuri.org/") String cuenta,
			@WebParam(name = "referencia", targetNamespace = "http://tempuri.org/") String referencia,
			@WebParam(name = "lote", targetNamespace = "http://tempuri.org/") String lote,
			@WebParam(name = "cupon", targetNamespace = "http://tempuri.org/") String cupon,
			@WebParam(name = "idproducto", targetNamespace = "http://tempuri.org/") String idproducto,
			@WebParam(name = "cantidad", targetNamespace = "http://tempuri.org/") String cantidad);

	/**
	 * 
	 * @param secuencial
	 * @param terminal
	 * @param iso
	 * @param cupon
	 * @return returns java.lang.String
	 */
	@WebMethod(action = "http://tempuri.org/validacionCupon")
	@WebResult(name = "validacionCuponResult", targetNamespace = "http://tempuri.org/")
	@RequestWrapper(localName = "validacionCupon", targetNamespace = "http://tempuri.org/", className = "org.tempuri.ValidacionCupon")
	@ResponseWrapper(localName = "validacionCuponResponse", targetNamespace = "http://tempuri.org/", className = "org.tempuri.ValidacionCuponResponse")
	public String validacionCupon(
			@WebParam(name = "iso", targetNamespace = "http://tempuri.org/") String iso,
			@WebParam(name = "terminal", targetNamespace = "http://tempuri.org/") String terminal,
			@WebParam(name = "cupon", targetNamespace = "http://tempuri.org/") String cupon,
			@WebParam(name = "secuencial", targetNamespace = "http://tempuri.org/") String secuencial);

}
